apiVersion: v1
kind: Secret
metadata:
  namespace: <your_namespace>
  name: <your_secret_name>
type: Opaque
stringData:
  POSTGRES_USER: <your_username>
  POSTGRES_PASSWORD: <your_encoded_password>
  POSTGRES_DB: <your_database>
  POSTGRES_NON_ROOT_USER: <your_username>
  POSTGRES_NON_ROOT_PASSWORD: <your encoded_password>